version: "3.5"

services:

  mysql:
    image: mysql:5.7
    container_name: "MySQL"
    command: --max_allowed_packet=32505856
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "db_study"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql

              
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: "PHPMyAdmin"
    links:
      - mysql
    ports:
      - 7070:80
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=3000000000

  api:
    build: ./docker
    container_name: "APIGoLang"
    ports:
      - 8000:8000
    environment:
      ACCESS_SECRET: "API123456"
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_USER: "root"
      DB_PASS: "123456"
      DB_NAME: "db_study"

        